<html>

<head>
<meta http-equiv="content-type" content="text/html; charset=euc-kr">
<title> 대원산업(주)에 오신걸 환영합니다.</title>
<meta name="generator" content="Namo WebEditor">


</head>

<body bgcolor="white" text="black" link="blue" vlink="purple" alink="red">
<table cellpadding="0" cellspacing="0" width="960" bgcolor="#F0F0F0" align="center">
    <tr>
        <td width="960">
            <p align="center">&nbsp;</p>
        </td>
    </tr>
    <tr>
        <td width="960" height="7">
            <p align="center"><font size="2">인천광역시 부평구 청천2동 412-1 &nbsp;&nbsp;&nbsp;&nbsp;Tel : (032) 516-2211 &nbsp;&nbsp;&nbsp;&nbsp;Fax : (032) 516-2246</font></p>
        </td>
    </tr>
    <tr>
        <td width="960" height="24">
            <p align="center"><font size="2">Copyright(c) 2002 &nbsp;&nbsp;&nbsp;&nbsp;DAEWON INDUSTRIAL CO., LTD. &nbsp;&nbsp;&nbsp;&nbsp;All rights Reserved.</font></p>
        </td>
    </tr>
</table>
</body>

</html>