<html>

<head>
<meta http-equiv="content-type" content="text/html; charset=euc-kr">
<title> 대원산업(주)에 오신걸 환영합니다.</title>
<meta name="generator" content="Namo WebEditor">



<!-- 스타일시트를 이용한 링크에 점선으로된 라인생기는 소스 시작 -->
<style type="text/css">
p,br,body,td,select,input,form,textarea,option { font-size:8pt;font-family:verdana ; }
A:link    {color:#5A5B74; text-decoration:none}
A:visited {color:#5A5B74; text-decoration:none}
A:active  {color:#5A5B74; text-decoration:none}
A:hover   {color:#A5A6C1; background-image: url(http://www.daewon-ind.co.kr/images/Link_Bar.GIF); background-position:bottom; background-repeat:repeat-x; text-decoration:none}
    body {
        scrollbar-face-color:#ffffff;
        scrollbar-shadow-color:#8788A9;
        scrollbar-highlight-color:#f3f3f3;
        scrollbar-3dlight-color:#ffffff;
        scrollbar-darkshadow-color:#ffffff;
        scrollbar-track-color:#ffffff;
        scrollbar-arrow-color:#8788A9
}
</style>
<!-- 스타일시트를 이용한 링크에 점선으로된 라인생기는 소스 끝 -->
<script language="JavaScript">
<!--
function na_restore_img_src(name, nsdoc)
{
  var img = eval((navigator.appName.indexOf('Netscape', 0) != -1) ? nsdoc+'.'+name : 'document.all.'+name);
  if (name == '')
    return;
  if (img && img.altsrc) {
    img.src    = img.altsrc;
    img.altsrc = null;
  } 
}

function na_preload_img()
{ 
  var img_list = na_preload_img.arguments;
  if (document.preloadlist == null) 
    document.preloadlist = new Array();
  var top = document.preloadlist.length;
  for (var i=0; i < img_list.length-1; i++) {
    document.preloadlist[top+i] = new Image;
    document.preloadlist[top+i].src = img_list[i+1];
  } 
}

function na_change_img_src(name, nsdoc, rpath, preload)
{ 
  var img = eval((navigator.appName.indexOf('Netscape', 0) != -1) ? nsdoc+'.'+name : 'document.all.'+name);
  if (name == '')
    return;
  if (img) {
    img.altsrc = img.src;
    img.src    = rpath;
  } 
}

// -->
</script>
</head>

<body bgcolor="white" text="black" link="blue" vlink="purple" alink="red" OnLoad="na_preload_img(false, '../images/Dw_Logo_C_Home.jpg');">
<table cellpadding="0" cellspacing="0" width="960" align="center" height="210" background="../images/bg_main_menu.JPG">
    <tr>
        <td width="764" height="30" colspan="5">
            <p align="center">&nbsp;</p>
        </td>
        <td width="72" height="30">&nbsp;</td>
        <td width="44" height="30">&nbsp;</td>
        <td width="80" height="30">
            <p align="center"><font size="2" color="blue">
			<a href="http://www.daewon-ind.co.kr/main_k.php" target="_self">
			<b>Korean</b></a></font></p>
        </td>
    </tr>
    <tr>
        <td width="120" height="60">
            <p align="center"><a href="http://www.daewon-ind.co.kr/main_e.php" OnMouseOut="na_restore_img_src('image1', 'document')" OnMouseOver="na_change_img_src('image1', 'document', '../images/Dw_Logo_C_Home.jpg', true);"><img src="../images/Dw_Logo.jpg" width="95" height="55" border="0" name="image1"></a></p>
        </td>
        <td width="284" height="60">
            <p><b><font size="2">&nbsp;DAEWON INDUSTRIAL CO., LTD.</font><font size="4"></font></b></p>
        </td>
        <td width="120" height="60" align="center" valign="middle">
            <p align="center"><font size="2" color="blue">
			<a href="../company/e_com_greeting.php" target="_self">
			<b>Company Information</b></a></font></p>
        </td>
        
        <td width="120" height="60">
            <p align="center"><font size="2" color="blue">
			<a href="../product/e_prd_pouch.php" target="_self">
			<b>Product Information</b></a></font></p>
        </td>
		
        <td width="120" height="60">
            <p align="center"><font size="2" color="blue">
			<a href="../process/e_prc_extrusion.php" target="_self">
			<b>Manufacturing Process</b></a></font></p>
        </td>
		
		
        <td width="72" height="60">
            <p align="center">&nbsp;</p>
        </td>
		
        <td width="124" height="60" colspan="2">
            <p align="center"><font size="2" color="blue">
			<a href="mailto:dwicl@daewon-ind.co.kr" target="_self">
			<b>Contact us</b></a></font></p>
        </td>
		
    </tr>
    <tr>
        <td width="960" height="120" colspan="8">&nbsp;</td>
    </tr>
</table>
</body>

</html>