<?php
$header = "
<html>
<head>
<title>jboard</title>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">
<style type=\"text/css\">
<!--
td,body {  font-family: \"굴림\"; font-size: 9pt}
INPUT, TEXTAREA, SELECT {  border: 1px #CCCCCC solid; background-color: #FFFFFF;  font-size: 9pt}
a:link,a:visited{text-decoration:none}
a:hover {text-decoration:underline}
-->
</style>
<body bgcolor=\"#FFFFFF\" text=\"#000000\" link=\"#000000\" vlink=\"#000000\" alink=\"#333333\">
";
?>
